version: "3.3"

services:

  ubuntu-xfce-vnc-rpa:
    image: delpinos/ubuntu-xfce-vnc-rpa
    container_name: ubuntu-xfce-vnc-rpa
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5901:5901
      - 6901:6901
    networks:
      - external-net
    restart: always
    privileged: true
    tty: true

networks:
  external-net:
    external:
      name: ${NETWORK}